#if defined(__EMSCRIPTEN__)
#include "Input_web.h"
#include <emscripten.h>
#include <algorithm>
#include <cwchar>
#include <sstream>
namespace ffx {
EM_JS(int, js_key_down, (int c), { return globalThis.FFXWeb && FFXWeb.input.keyDown(c) ? 1:0; });
EM_JS(int, js_last_key, (), { return globalThis.FFXWeb ? FFXWeb.input.takeLastKey() : -1; });
EM_JS(int, js_pad_down, (int pad,int code), { return globalThis.FFXWeb && FFXWeb.input.padCodeDown(pad,code) ? 1:0; });
Input::Input(){resetDefaults();}
void Input::edges(InputState& c,const InputState& p){c.leftPressed=c.left&&!p.left;c.rightPressed=c.right&&!p.right;c.upPressed=c.up&&!p.up;c.downPressed=c.down&&!p.down;c.attackPressed=c.attack&&!p.attack;c.attack2Pressed=c.attack2&&!p.attack2;c.jumpPressed=c.jump&&!p.jump;c.specialPressed=c.special&&!p.special;c.startPressed=c.start&&!p.start;c.backPressed=c.back&&!p.back;}
static int defKey(size_t p,InputAction a){static constexpr int defs[3][10]={{VK_LEFT,VK_RIGHT,VK_UP,VK_DOWN,'J','I','K','L',VK_RETURN,VK_ESCAPE},{VK_NUMPAD4,VK_NUMPAD6,VK_NUMPAD8,VK_NUMPAD2,VK_NUMPAD1,VK_NUMPAD7,VK_NUMPAD3,VK_NUMPAD5,VK_NUMPAD0,VK_DECIMAL},{'F','H','T','G','Y','O','U','P','3','4'}};return defs[std::min<size_t>(p,2)][(size_t)a];}
static int defPad(InputAction a){switch(a){case InputAction::Left:return (int)PadCode::MoveLeft;case InputAction::Right:return (int)PadCode::MoveRight;case InputAction::Up:return (int)PadCode::MoveUp;case InputAction::Down:return (int)PadCode::MoveDown;case InputAction::Attack:return (int)PadCode::X;case InputAction::Attack2:return (int)PadCode::Y;case InputAction::Jump:return (int)PadCode::A;case InputAction::Special:return (int)PadCode::B;case InputAction::Start:return (int)PadCode::Start;case InputAction::Back:return (int)PadCode::Back;default:return 0;}}
void Input::resetDefaults(){for(size_t p=0;p<MaxPlayers;++p)resetPlayerDefaults(p);} void Input::resetPlayerDefaults(size_t p){if(p>=MaxPlayers)return;auto&b=bindings_[p];b.keyboardEnabled=true;b.gamepadIndex=(int)p;for(size_t a=0;a<ActionCount;++a){b.keyboard[a]=defKey(p,(InputAction)a);b.gamepad[a]=defPad((InputAction)a);}}
void Input::setKeyboardBinding(size_t p,InputAction a,int vk){if(p<MaxPlayers&&vk>=0&&vk<256)bindings_[p].keyboard[(size_t)a]=vk;} void Input::setGamepadBinding(size_t p,InputAction a,int code){if(p<MaxPlayers&&code>=0&&code<=(int)PadCode::MoveRight)bindings_[p].gamepad[(size_t)a]=code;} void Input::setKeyboardEnabled(size_t p,bool e){if(p<MaxPlayers)bindings_[p].keyboardEnabled=e;} void Input::setGamepadIndex(size_t p,int i){if(p<MaxPlayers)bindings_[p].gamepadIndex=std::clamp(i,-1,3);}
void Input::update(){
    prev_=cur_;uiPrev_=ui_;for(auto&s:cur_)s={};ui_={};rawKeyPrev_=rawKeyCur_;lastKeyboardPress_=js_last_key();
    for(int vk=1;vk<256;++vk)rawKeyCur_[(size_t)vk]=js_key_down(vk)!=0;
    padPrev_=padCur_;lastGamepadPress_.fill(-1);for(int p=0;p<4;++p){for(int code=1;code<=28;++code){bool d=js_pad_down(p,code)!=0;padCur_[(size_t)p][(size_t)code]=d;if(d&&!padPrev_[(size_t)p][(size_t)code]&&lastGamepadPress_[(size_t)p]<0)lastGamepadPress_[(size_t)p]=code;}}
    for(size_t p=0;p<MaxPlayers;++p){auto&s=cur_[p];const auto&b=bindings_[p];auto down=[&](InputAction a){size_t ai=(size_t)a;bool v=b.keyboardEnabled&&b.keyboard[ai]>=0&&b.keyboard[ai]<256&&rawKeyCur_[(size_t)b.keyboard[ai]];if(b.gamepadIndex>=0&&b.gamepadIndex<4){int code=b.gamepad[ai];if(code>0&&code<=28)v|=padCur_[(size_t)b.gamepadIndex][(size_t)code];}return v;};s.left=down(InputAction::Left);s.right=down(InputAction::Right);s.up=down(InputAction::Up);s.down=down(InputAction::Down);s.attack=down(InputAction::Attack);s.attack2=down(InputAction::Attack2);s.jump=down(InputAction::Jump);s.special=down(InputAction::Special);s.start=down(InputAction::Start);s.back=down(InputAction::Back);edges(s,prev_[p]);}
    ui_=cur_[0];auto kd=[&](int k){return k>=0&&k<256&&rawKeyCur_[(size_t)k];};ui_.left|=kd(VK_LEFT)||kd('A');ui_.right|=kd(VK_RIGHT)||kd('D');ui_.up|=kd(VK_UP)||kd('W');ui_.down|=kd(VK_DOWN)||kd('S');ui_.start|=kd(VK_RETURN);ui_.attack|=kd('J');ui_.back|=kd(VK_ESCAPE);for(int code:{(int)PadCode::DPadLeft,(int)PadCode::LSLeft})ui_.left|=padCur_[0][(size_t)code];for(int code:{(int)PadCode::DPadRight,(int)PadCode::LSRight})ui_.right|=padCur_[0][(size_t)code];for(int code:{(int)PadCode::DPadUp,(int)PadCode::LSUp})ui_.up|=padCur_[0][(size_t)code];for(int code:{(int)PadCode::DPadDown,(int)PadCode::LSDown})ui_.down|=padCur_[0][(size_t)code];ui_.attack|=padCur_[0][(size_t)PadCode::A];ui_.start|=padCur_[0][(size_t)PadCode::Start];ui_.back|=padCur_[0][(size_t)PadCode::B]||padCur_[0][(size_t)PadCode::Back];edges(ui_,uiPrev_);
}
int Input::takeLastKeyboardPress(){int v=lastKeyboardPress_;lastKeyboardPress_=-1;return v;} int Input::takeLastGamepadPress(int i){if(i<0||i>=4)return -1;int v=lastGamepadPress_[(size_t)i];lastGamepadPress_[(size_t)i]=-1;return v;} void Input::clearCaptureEvents(){lastKeyboardPress_=-1;lastGamepadPress_.fill(-1);}
const wchar_t* Input::actionName(InputAction a){switch(a){case InputAction::Left:return L"ESQUERDA";case InputAction::Right:return L"DIREITA";case InputAction::Up:return L"CIMA";case InputAction::Down:return L"BAIXO";case InputAction::Attack:return L"ATAQUE";case InputAction::Attack2:return L"ATAQUE 2";case InputAction::Jump:return L"PULO";case InputAction::Special:return L"ESPECIAL";case InputAction::Start:return L"START/PAUSE";case InputAction::Back:return L"VOLTAR";default:return L"?";}}
const char* Input::actionSettingName(InputAction a){switch(a){case InputAction::Left:return "left";case InputAction::Right:return "right";case InputAction::Up:return "up";case InputAction::Down:return "down";case InputAction::Attack:return "attack";case InputAction::Attack2:return "attack2";case InputAction::Jump:return "jump";case InputAction::Special:return "special";case InputAction::Start:return "start";case InputAction::Back:return "back";default:return "unknown";}}
std::wstring Input::keyName(int vk){if(vk>='A'&&vk<='Z')return std::wstring(1,(wchar_t)vk);if(vk>='0'&&vk<='9')return std::wstring(1,(wchar_t)vk);switch(vk){case VK_LEFT:return L"LEFT";case VK_RIGHT:return L"RIGHT";case VK_UP:return L"UP";case VK_DOWN:return L"DOWN";case VK_RETURN:return L"ENTER";case VK_ESCAPE:return L"ESC";case VK_SPACE:return L"SPACE";case VK_NUMPAD0:return L"NUM0";case VK_NUMPAD1:return L"NUM1";case VK_NUMPAD2:return L"NUM2";case VK_NUMPAD3:return L"NUM3";case VK_NUMPAD4:return L"NUM4";case VK_NUMPAD5:return L"NUM5";case VK_NUMPAD6:return L"NUM6";case VK_NUMPAD7:return L"NUM7";case VK_NUMPAD8:return L"NUM8";case VK_NUMPAD9:return L"NUM9";case VK_DECIMAL:return L"NUM.";default:return L"KEY "+std::to_wstring(vk);}}
const wchar_t* Input::padName(int c){switch((PadCode)c){case PadCode::DPadUp:return L"DPAD UP";case PadCode::DPadDown:return L"DPAD DOWN";case PadCode::DPadLeft:return L"DPAD LEFT";case PadCode::DPadRight:return L"DPAD RIGHT";case PadCode::A:return L"A";case PadCode::B:return L"B";case PadCode::X:return L"X";case PadCode::Y:return L"Y";case PadCode::LB:return L"LB";case PadCode::RB:return L"RB";case PadCode::Back:return L"BACK";case PadCode::Start:return L"START";case PadCode::LThumb:return L"L3";case PadCode::RThumb:return L"R3";case PadCode::LT:return L"LT";case PadCode::RT:return L"RT";case PadCode::LSUp:return L"LS UP";case PadCode::LSDown:return L"LS DOWN";case PadCode::LSLeft:return L"LS LEFT";case PadCode::LSRight:return L"LS RIGHT";case PadCode::RSUp:return L"RS UP";case PadCode::RSDown:return L"RS DOWN";case PadCode::RSLeft:return L"RS LEFT";case PadCode::RSRight:return L"RS RIGHT";case PadCode::MoveUp:return L"MOVE UP";case PadCode::MoveDown:return L"MOVE DOWN";case PadCode::MoveLeft:return L"MOVE LEFT";case PadCode::MoveRight:return L"MOVE RIGHT";default:return L"NONE";}}
}
#endif
